# Generated by Django 2.0.5 on 2019-02-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_num', models.CharField(max_length=20, verbose_name='测试集编号')),
                ('name', models.CharField(max_length=18, verbose_name='测试集名称')),
                ('detail', models.CharField(max_length=50, verbose_name='测试集描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('belong_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试集',
                'verbose_name_plural': '测试集',
            },
        ),
    ]
