# Generated by Django 2.0.5 on 2019-02-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='计划名称')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='测试项目')),
            ],
        ),
    ]
