# Generated by Django 2.0.5 on 2019-02-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '测试计划', 'verbose_name_plural': '测试计划'},
        ),
    ]
