# Generated by Django 2.0.5 on 2019-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(verbose_name='步骤顺序号')),
                ('name', models.CharField(max_length=18, verbose_name='操作步骤名称')),
                ('doc', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作步骤描述')),
                ('remark', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '操作步骤库',
                'verbose_name_plural': '操作步骤库',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_num', models.CharField(max_length=20, verbose_name='用例编号')),
                ('name', models.CharField(max_length=18, verbose_name='用例标题')),
                ('type', models.CharField(choices=[('web', 'Web自动化'), ('app', 'App自动化'), ('inface', '接口自动化')], default='web', max_length=20, verbose_name='用例类型')),
                ('expect', models.CharField(max_length=50, verbose_name='期望结果')),
                ('status', models.CharField(choices=[('idle', '未执行'), ('success', '通过'), ('fail', '失败')], default='idle', max_length=20, verbose_name='结果')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='low', max_length=20, verbose_name='用例级别')),
                ('detail', models.CharField(max_length=50, verbose_name='用例描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用例库',
                'verbose_name_plural': '用例库',
            },
        ),
    ]
