# Generated by Django 2.0.5 on 2019-02-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='关键字名称')),
                ('doc', models.CharField(max_length=50, verbose_name='关键字描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '关键字库',
                'verbose_name_plural': '关键字库',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Library名称')),
                ('doc', models.CharField(max_length=50, verbose_name='Library名描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '公用测试库',
                'verbose_name_plural': '公用测试库',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Resource名称')),
                ('doc', models.CharField(max_length=100, verbose_name='Resource描述')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'Resource库',
                'verbose_name_plural': 'Resource库',
            },
        ),
        migrations.CreateModel(
            name='UserKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户关键字名称')),
                ('doc', models.CharField(max_length=100, verbose_name='用户关键字描述')),
                ('args', models.CharField(max_length=100, verbose_name='参数')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.Keyword')),
                ('relate_user_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.UserKeywords', verbose_name='关联用户关键字')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.Resource', verbose_name='所属Resource')),
            ],
            options={
                'verbose_name': '用户关键字库',
                'verbose_name_plural': '用户关键字库',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.Library', verbose_name='所属Library'),
        ),
    ]
