# Generated by Django 2.0.5 on 2019-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('type', models.CharField(choices=[('web', 'Web自动化'), ('app', 'App自动化'), ('inface', '接口自动化')], max_length=30, verbose_name='项目名称')),
                ('url', models.URLField(verbose_name='项目地址')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('edit_time', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '测试项目',
                'verbose_name_plural': '测试项目',
            },
        ),
    ]
