# Generated by Django 2.0.5 on 2019-02-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190213_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=100, verbose_name='项目地址'),
        ),
    ]
